#some examples here : https://github.com/rethinkdb/horizon-thinkmark/blob/master/schema.toml

[groups.admin.rules.carte_blanche]
template = "any()"


[groups.authenticated.rules.read_own_info]
template = "collection('users').find({id: userId()})"

[groups.authenticated.rules.write_own_info]
template = "collection('users').store({id: userId(), nicknm: any(), email: any()})"

[groups.authenticated.rules.nodes_store]
template = "collection('nodes').store(any())"
[groups.authenticated.rules.nodes_replace]
template = "collection('nodes').replace(any())"
[groups.authenticated.rules.nodes_remove]
template = "collection('nodes').remove(any())"

[groups.authenticated.rules.contribution_history_write]
template = "collection('nodesHistory').store(any())"

[groups.authenticated.rules.pref]
template = "collection('userPref').upsert({id: userId(), openNodes: any()})"