
[collections.nodes]
[[collections.nodes.indexes]]
fields = [["id,order"]]
[[collections.nodes.indexes]]
fields = [["order"]]

[collections.users]

[collections.userPref]

[collections.nodesHistory]

[groups.authenticated]
[groups.authenticated.rules.contribution_history_suscribe]
template = "collection('nodesHistory').watch()"
[groups.authenticated.rules.contribution_history_write]
template = "collection('nodesHistory').store(any())"
[groups.authenticated.rules.nodes_suscribe]
template = "collection('nodes').watch()"
[groups.authenticated.rules.nodes_fetch]
template = "collection('nodes').order('order').fetch()"
[groups.authenticated.rules.nodes_remove]
template = "collection('nodes').remove(any())"
[groups.authenticated.rules.nodes_replace]
template = "collection('nodes').replace(any())"
[groups.authenticated.rules.nodes_store]
template = "collection('nodes').store(any())"
[groups.authenticated.rules.foldStatusRead]
template = "collection('userPref').find({id: userId()})"
#[groups.authenticated.rules.foldStatusWriteFirst]
#template = "collection('userPref').insert({id: userId(), openNodes: any()})"
#[groups.authenticated.rules.foldStatusWrite]
#template = "collection('userPref').replace({id: userId(), openNodes: any()})"
[groups.authenticated.rules.foldStatusWrite]
template = "collection('userPref').anyWrite()"
[groups.authenticated.rules.read_own_info]
template = "collection('users').find({id: userId()})"
[groups.authenticated.rules.write_own_info]
template = "collection('users').anyWrite()"

[groups.admin]
[groups.admin.rules.carte_blanche]
template = "any()"
